name: aws-cli-tool  # プロジェクト名を明示的に設定
services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack
    ports:
      - "4566:4566"
      - "27017:27017"
    environment:
      - SERVICES=sqs,dynamodb,docdb
      - SQS_ENDPOINT_STRATEGY=off
      - AWS_DEFAULT_REGION=ap-northeast-1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - MONGO_EXTERNAL_PORT=27017
    volumes:
      - "./init:/etc/localstack/init/ready.d"
