name: aws-cli-tool  # プロジェクト名を明示的に設定
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,dynamodb
      - SQS_ENDPOINT_STRATEGY=off
      - AWS_DEFAULT_REGION=ap-northeast-1
    volumes:
      - "./init:/etc/localstack/init/ready.d"

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password123
